// Explanations and examples are teaching synthesis. Chapter links retain the full source register.
export const CORE_TERMS = [
  {term: 'CDC', whyEn: "Keep analytical copies current without repeatedly copying every source row; define how updates and deletes affect the result.", whyKo: "원본의 모든 행을 반복 복사하지 않고 분석용 사본을 갱신할 때 쓴다. 수정·삭제를 결과에 어떻게 반영할지도 정해야 한다.", english: 'Change Data Capture records inserts, updates, and deletes so another system can follow database changes.', korean: '변경 데이터 캡처다. 데이터베이스의 추가·수정·삭제를 변경 기록으로 전달해 다른 시스템이 따라가게 한다.', exampleEn: "An order changes from pending to paid, but analytics still shows pending. → Capture the change and apply it downstream using the order identity. → Check freshness and replay handling so the update does not become a second sale.", exampleKo: "주문이 결제 대기에서 완료로 바뀌었는데 분석 화면은 그대로다. → 변경을 포착해 주문 식별자로 분석 저장소에 반영한다. → 반영 지연과 재처리를 확인해 수정이 두 번째 매출로 계산되지 않게 한다.", distinctionEn: 'CDC captures changes; dbt transforms already loaded data. A row update is not automatically another sale.', distinctionKo: 'CDC는 변경을 수집하고 dbt는 이미 적재한 데이터를 변환한다. 행 수정 한 번이 새 매출 한 건은 아니다.', source: 'https://debezium.io/documentation/reference/stable/architecture.html', chapter: 'data-observability-engineering-kafka-cdc-streaming'},
  {term: 'dbt', whyEn: "Replace scattered transformation SQL with reusable models, explicit dependencies, tests, and documentation shared by the team.", whyKo: "흩어진 변환 SQL을 팀이 공유하는 재사용 모델·명시적 의존성·검사·문서로 관리할 때 쓴다.", english: 'A tool for organizing, running, testing, and documenting data transformations, commonly written as SQL models.', korean: '주로 SQL 모델로 작성한 데이터 변환을 연결·실행·검사·문서화하는 도구다. 모델은 분석용 테이블이나 뷰를 만드는 변환 정의다.', exampleEn: "Two teams report different daily revenue from the same loaded orders. → Build shared cleaned-order and revenue SQL models with dependencies and key tests. → Reconcile totals against a small fixture containing duplicates and refunds.", exampleKo: "같은 적재 주문으로 두 팀이 서로 다른 일일 매출을 보고한다. → 의존성과 키 검사를 갖춘 공통 정제 주문·매출 SQL 모델을 만든다. → 중복과 환불을 포함한 작은 예제 데이터로 합계를 대조한다.", distinctionEn: 'dbt is neither the database holding the rows nor the CDC connector collecting source changes. A successful build still needs business checks.', distinctionKo: 'dbt는 행을 보관하는 데이터베이스나 변경을 가져오는 CDC 커넥터가 아니다. 빌드에 성공해도 업무 규칙 검사는 필요하다.', source: 'https://docs.getdbt.com/docs/introduction', chapter: 'data-observability-engineering-modeling-orchestration'},
  {term: 'Debezium', whyEn: "Capture supported database changes with existing connectors instead of building every change reader and restart protocol yourself.", whyKo: "변경 읽기와 재시작 절차를 모두 직접 만들기보다 기존 커넥터로 지원 데이터베이스의 변경을 수집할 때 쓴다.", english: 'Connectors that turn supported source-database changes into change events.', korean: '지원 데이터베이스의 변경을 변경 이벤트로 바꾸는 커넥터다. CDC를 구현하는 도구 중 하나다.', exampleEn: "An analytics copy needs PostgreSQL order updates without repeated full exports. → Configure the supported connector's snapshot and change-stream workflow. → Restart it in a controlled test and verify change coverage and downstream duplicate handling.", exampleKo: "분석 사본에 전체 내보내기를 반복하지 않고 PostgreSQL 주문 수정을 반영해야 한다. → 지원 커넥터의 스냅샷·변경 스트림 흐름을 설정한다. → 통제된 재시작 시험으로 변경 수집 범위와 후속 중복 처리를 확인한다.", distinctionEn: 'CDC is the approach; Debezium is an implementation. Kafka Connect hosts connectors separately from Kafka brokers.', distinctionKo: 'CDC는 접근 방식이고 Debezium은 구현이다. Kafka Connect의 커넥터 실행 역할과 Kafka 브로커의 저장 역할도 다르다.', source: 'https://debezium.io/documentation/reference/stable/architecture.html', chapter: 'data-observability-engineering-kafka-cdc-streaming'},
  {term: 'Kafka', whyEn: "Decouple event producers from consumers and retain records for independent processing and replay under a defined retention policy.", whyKo: "생산자와 소비자의 실행을 분리하고 정해진 보존 정책 안에서 독립적인 처리·재생을 위한 이벤트를 남길 때 쓴다.", english: 'An event-streaming platform that stores records in partitioned logs for producers and consumers.', korean: '생산자가 보낸 이벤트를 파티션 로그에 보관하고 소비자가 읽게 하는 이벤트 스트리밍 플랫폼이다.', exampleEn: "The analytics consumer is offline while orders continue arriving. → Retain events in partitioned logs and resume from recorded consumer positions. → Confirm retention covered the outage and replay produces the intended state.", exampleKo: "분석 소비자가 멈췄지만 주문은 계속 들어온다. → 파티션 로그에 이벤트를 보관하고 기록한 소비 위치에서 재개한다. → 보존 기간이 중단 시간을 포함했고 재생 결과가 의도한 상태인지 확인한다.", distinctionEn: 'Storing and delivering an event does not compute its revenue or make an external effect happen exactly once.', distinctionKo: '이벤트를 보관·전달하는 것만으로 매출이 계산되거나 외부 효과가 정확히 한 번 발생하지는 않는다.', source: 'https://kafka.apache.org/41/getting-started/introduction/', chapter: 'data-observability-engineering-kafka-cdc-streaming'},
  {term: 'Spark', whyEn: "Distribute large data transformations when one process is insufficient, then verify that parallel work outweighs coordination and shuffle costs.", whyKo: "프로세스 하나로 감당하기 어려운 데이터 변환을 분산할 때 쓴다. 병렬 처리의 이득이 조정·셔플 비용보다 큰지도 검증한다.", english: 'A distributed processing engine that turns transformations into tasks run by executors coordinated by a driver.', korean: '변환을 여러 태스크로 나누고 드라이버가 실행기들을 조정해 처리하는 분산 계산 엔진이다.', exampleEn: "A daily aggregation no longer fits comfortably on one machine. → Distribute the transformation and inspect stages, shuffle, and skew. → Compare correctness, runtime, and resource cost with the existing approach.", exampleKo: "일일 집계를 한 대의 장비에서 처리하기 어려워졌다. → 변환을 분산하고 스테이지·셔플·쏠림을 살핀다. → 기존 방식과 정확성·실행 시간·자원 비용을 비교한다.", distinctionEn: 'Spark computes; a table format defines committed table state and storage retains the files.', distinctionKo: 'Spark는 계산한다. 커밋된 테이블 상태는 테이블 형식이 정의하고 파일은 저장소가 보관한다.', source: 'https://spark.apache.org/docs/4.0.1/cluster-overview.html', chapter: 'data-observability-engineering-spark-performance'},
  {term: 'Parquet', whyEn: "Reduce analytical reading and storage work through column-oriented layout and compression when queries need selected fields.", whyKo: "분석 쿼리에 일부 필드가 필요할 때 열 중심 배치와 압축으로 읽기·저장 작업량을 줄이기 위해 쓴다.", english: 'A column-oriented file format for analytical data, with encoding and compression.', korean: '분석 데이터를 열 중심으로 저장하며 인코딩·압축을 사용하는 파일 형식이다.', exampleEn: "A revenue query needs date and amount from a wide order dataset. → Store analytical data in Parquet and select the required columns. → Compare bytes read and output totals against the same source data.", exampleKo: "열이 많은 주문 데이터에서 매출 쿼리는 날짜와 금액만 필요하다. → 분석 데이터를 Parquet로 저장하고 필요한 열을 선택한다. → 같은 원본을 기준으로 읽은 바이트와 합계를 비교한다.", distinctionEn: 'Parquet describes one file; it does not by itself define an atomic table update across many files.', distinctionKo: 'Parquet는 파일을 설명한다. 여러 파일의 원자적 테이블 갱신은 형식 하나만으로 정의되지 않는다.', source: 'https://parquet.apache.org/docs/overview/', chapter: 'data-observability-engineering-parquet-object-storage'},
  {term: 'Iceberg', whyEn: "Give readers an identified committed table state while coordinating file changes, schema evolution, and retained snapshots.", whyKo: "파일 변경·스키마 진화·스냅샷 보존을 조정하면서 독자에게 식별 가능한 커밋 테이블 상태를 제공할 때 쓴다.", english: 'A table format that records schemas, snapshots, and file metadata so engines can read committed analytical tables.', korean: '스키마·스냅샷·파일 메타데이터를 기록해 엔진이 커밋된 분석 테이블을 읽게 하는 테이블 형식이다.', exampleEn: "Readers must see a coherent table while a writer replaces several files. → Commit the new file set through Iceberg snapshot metadata. → Verify readers resolve an accepted snapshot and retained versions still have their referenced files.", exampleKo: "작성자가 여러 파일을 교체하는 동안 독자는 일관된 테이블을 읽어야 한다. → Iceberg 스냅샷 메타데이터를 통해 새 파일 집합을 커밋한다. → 독자가 승인된 스냅샷을 읽고 보존 버전의 참조 파일도 남아 있는지 확인한다.", distinctionEn: 'It is not the storage service or the query engine. Retained metadata also needs its referenced files.', distinctionKo: '저장 서비스나 쿼리 엔진 자체는 아니다. 보존한 메타데이터가 참조하는 파일도 남아 있어야 한다.', source: 'https://iceberg.apache.org/docs/latest/', chapter: 'data-observability-engineering-table-formats'},
  {term: 'Delta Lake', whyEn: "Coordinate accepted changes over data files through a transaction log so readers and recovery can reference table versions.", whyKo: "트랜잭션 로그로 데이터 파일의 승인된 변경을 조정하고 읽기·복구가 테이블 버전을 참조하도록 할 때 쓴다.", aliases: ['Delta'], english: 'A table layer whose transaction log identifies committed changes over data files.', korean: '트랜잭션 로그로 데이터 파일 위의 커밋된 변경을 식별하는 테이블 계층이다.', exampleEn: "A correction changes order totals, and analysts need to compare before and after. → Record the relevant Delta table versions and use supported versioned reads. → Reconcile totals while checking that retention preserves the required data files.", exampleKo: "주문 수정으로 합계가 바뀌어 전후 비교가 필요하다. → 관련 Delta 테이블 버전을 기록하고 지원되는 버전 조회를 사용한다. → 필요한 데이터 파일이 보존되는지 확인하며 합계를 대조한다.", distinctionEn: 'The Delta log is not a Spark streaming checkpoint; they retain different state.', distinctionKo: 'Delta 로그와 Spark 스트리밍 체크포인트는 서로 다른 상태를 보존한다.', chapter: 'data-observability-engineering-table-formats'},
  {term: 'Airflow', whyEn: "Schedule dependent tasks for explicit intervals and inspect retries or missing runs instead of relying on manually ordered commands.", whyKo: "수동 명령 순서에 의존하지 않고 명시한 구간의 의존 작업을 예약하며 재시도·누락 실행을 확인할 때 쓴다.", english: 'A workflow orchestrator that schedules tasks and their dependencies.', korean: '작업과 의존성을 정의하고 실행을 예약·조정하는 워크플로 도구다.', exampleEn: "Yesterday's revenue must publish only after ingestion and validation succeed. → Define interval-aware task dependencies and retry behavior in a workflow. → Simulate a failed dependency and verify publication waits and retries use the same interval.", exampleKo: "어제 매출은 수집과 검증이 성공한 뒤에만 공개해야 한다. → 워크플로에 데이터 구간을 고려한 의존성과 재시도를 정의한다. → 선행 실패 시 공개가 대기하고 재시도가 같은 구간을 쓰는지 시험한다.", distinctionEn: 'The scheduler coordinates work; the database or processing engine executes the transformation.', distinctionKo: '스케줄러는 실행을 조정하고 실제 변환은 데이터베이스나 처리 엔진이 수행한다.', chapter: 'data-observability-engineering-modeling-orchestration'},
  {term: 'Dagster', whyEn: "Organize orchestration around the datasets a team must deliver and inspect their dependencies and partition materialization.", whyKo: "팀이 제공해야 할 데이터셋을 중심으로 실행을 조직하고 의존성과 파티션별 생성 상태를 확인할 때 쓴다.", english: 'An orchestrator that can organize work around data assets and their dependencies.', korean: '데이터 자산과 의존성을 중심으로 작업을 조직할 수 있는 오케스트레이터다.', exampleEn: "A daily-revenue dataset is missing one date although other runs succeeded. → Model date-partitioned assets and inspect upstream dependencies and materializations. → Recompute the missing partition and validate its data before treating it as complete.", exampleKo: "다른 실행은 성공했지만 일일 매출 데이터셋에 하루가 빠졌다. → 날짜별 자산을 모델링하고 상류 의존성과 생성 기록을 살핀다. → 누락 파티션을 다시 계산하고 데이터를 검증한 뒤 완료로 판단한다.", distinctionEn: 'An asset update still needs correctness and publication checks; it is not a database transaction by itself.', distinctionKo: '자산 갱신에도 정확성·공개 검사가 필요하며 자체로 데이터베이스 트랜잭션이 되는 것은 아니다.', chapter: 'data-observability-engineering-modeling-orchestration'},
  {term: 'OpenTelemetry', whyEn: "Use shared instrumentation and context conventions across services while keeping telemetry transport separate from the chosen analysis backend.", whyKo: "여러 서비스가 공통 계측·문맥 규약을 쓰도록 하고 관측 데이터 전송을 선택한 분석 백엔드와 분리할 때 쓴다.", aliases: ['OTel'], english: 'APIs, SDKs, conventions, and collection components for instrumenting and transporting telemetry.', korean: '시스템을 계측하고 관측 데이터를 전달하기 위한 API·SDK·규약·수집 구성 요소다.', exampleEn: "A slow order request crosses services whose logs have unrelated identifiers. → Instrument operations and propagate trace context with consistent resource attributes. → Follow a controlled request across traces and correlated signals to locate the delay.", exampleKo: "느린 주문 요청이 식별자가 제각각인 여러 서비스 로그에 흩어져 있다. → 작업을 계측하고 일관된 리소스 속성과 추적 문맥을 전달한다. → 통제된 요청을 트레이스와 연결 신호로 따라가 지연 위치를 찾는다.", distinctionEn: 'Instrumentation and transport still need a backend for storage and queries.', distinctionKo: '계측·전송과 저장·질의는 다른 역할이므로 백엔드가 별도로 필요하다.', source: 'https://opentelemetry.io/docs/concepts/signals/', chapter: 'data-observability-engineering-opentelemetry'},
  {term: 'Prometheus', whyEn: "Measure operational trends and rates and evaluate metric-based alerts instead of inspecting every request individually.", whyKo: "모든 요청을 개별 조사하는 대신 운영 추세·비율을 측정하고 지표 기반 경보를 평가할 때 쓴다.", english: 'A monitoring system that stores and queries time-series metrics.', korean: '시간에 따라 기록된 지표를 저장하고 질의하는 모니터링 시스템이다.', exampleEn: "Operators need to know whether publication failures are increasing. → Record attempt and failure counters and query suitable rates. → Test the alert with controlled failures and separately check missing telemetry.", exampleKo: "운영자가 데이터 공개 실패가 늘고 있는지 알아야 한다. → 시도·실패 카운터를 기록하고 적절한 변화율을 조회한다. → 통제된 실패로 경보를 시험하고 관측 누락도 따로 검사한다.", distinctionEn: 'An operational metric is not an exact business ledger, and missing observations need their own checks.', distinctionKo: '운영 지표는 정확한 업무 장부가 아니며 관측 누락에는 별도 검사가 필요하다.', chapter: 'data-observability-engineering-metrics-logs-traces'},
  {term: 'Grafana', whyEn: "Bring relevant measurements and diagnostic links into a shared investigation view so responders can follow a problem across data sources.", whyKo: "관련 측정값·진단 링크를 공통 조사 화면에 모아 대응자가 여러 데이터 소스에 걸친 문제를 추적하도록 할 때 쓴다.", english: 'An interface for exploring data sources and building dashboards and diagnostic links.', korean: '데이터 소스를 탐색하고 대시보드·진단 링크를 구성하는 화면 도구다.', exampleEn: "Responders switch between disconnected metrics, logs, and trace screens. → Build a focused dashboard with consistent time ranges and diagnostic links. → Rehearse an incident and confirm each link reaches the relevant backend evidence.", exampleKo: "대응자가 서로 연결되지 않은 지표·로그·추적 화면을 오간다. → 시간 범위와 진단 링크를 맞춘 대시보드를 만든다. → 장애 대응을 연습하며 각 링크가 관련 백엔드 근거로 이어지는지 확인한다.", distinctionEn: 'A green panel does not repair data or prove that its backend observed every event.', distinctionKo: '녹색 패널이 데이터를 고치거나 백엔드가 모든 이벤트를 관측했음을 입증하지 않는다.', chapter: 'data-observability-engineering-metrics-logs-traces'},
  {term: 'OpenLineage', whyEn: "Record which datasets a run consumed and produced so teams can trace impact and investigate data changes across tools.", whyKo: "실행이 소비·생성한 데이터셋을 기록해 여러 도구에 걸친 변경 영향과 데이터 문제를 추적할 때 쓴다.", english: 'An event model for describing datasets, processing jobs, runs, and their derivation relationships.', korean: '데이터셋·처리 작업·실행과 파생 관계를 설명하는 이벤트 모델이다.', exampleEn: "A source schema change breaks a revenue report, and its path is unclear. → Capture job, run, and dataset relationships through supported integrations. → Follow the affected lineage and verify uncovered transformations in their source definitions.", exampleKo: "원본 스키마 변경으로 매출 보고서가 깨졌지만 경로가 불분명하다. → 지원 연동으로 잡·실행·데이터셋 관계를 수집한다. → 영향 계보를 따라가고 수집되지 않은 변환은 원본 정의에서 확인한다.", distinctionEn: 'Lineage explains derivation, while an OTel span records an operation; neither alone proves data accuracy.', distinctionKo: '계보는 파생 관계, OTel span은 작업을 기록한다. 어느 쪽도 단독으로 데이터 정확성을 입증하지 않는다.', chapter: 'data-observability-engineering-lineage-governance'},
];

let chapterTerms = [];
export function configureTerms(documents) {
  chapterTerms = documents.flatMap((doc) => (doc.terms ?? []).map((term) => ({...term, chapter: doc.id, topicId: doc.topicId})));
}

export function termsForDocument(currentDocument, glossary = chapterTerms) {
  const body = `${currentDocument.title} ${currentDocument.searchText}`;
  const rich = CORE_TERMS.filter((term) => [term.term, ...(term.aliases ?? [])].some((alias) => new RegExp(`(?<![A-Za-z0-9_])${escapePattern(alias)}(?![A-Za-z0-9_])`, 'i').test(body)));
  const known = new Set(rich.flatMap((term) => [term.term, ...(term.aliases ?? [])]).map((value) => value.toLowerCase()));
  const result = [...rich];
  for (const term of [...(currentDocument.terms ?? []), ...glossary.filter((item) => item.topicId === currentDocument.topicId && new RegExp(`(?<![A-Za-z0-9_])${escapePattern(item.term)}(?![A-Za-z0-9_])`, 'i').test(body))]) {
    if (known.has(term.term.toLowerCase())) continue;
    known.add(term.term.toLowerCase()); result.push(term);
  }
  return result;
}
function escapePattern(value) { return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'); }

export function attachTerms(article, currentDocument, {t}) {
  const terms = termsForDocument(currentDocument);
  const host = article.querySelector('[data-term-primer]');
  if (!terms.length) return;
  const introduction = document.createElement('details'); introduction.className = 'term-primer';
  const summary = document.createElement('summary'); summary.textContent = `${t('Terms in this chapter')} (${terms.length})`;
  introduction.append(summary);
  const hint = document.createElement('p'); hint.textContent = t('Select an underlined term to read its explanation.'); introduction.append(hint);
  const list = document.createElement('div'); list.className = 'term-chips'; introduction.append(list); host.append(introduction);
  const dialog = document.createElement('dialog'); dialog.className = 'term-dialog'; dialog.setAttribute('aria-labelledby', 'term-dialog-title'); article.append(dialog);
  const openTerm = (term) => {
    dialog.replaceChildren();
    const header = document.createElement('div'); header.className = 'term-dialog-header';
    const close = document.createElement('button'); close.type = 'button'; close.className = 'term-close'; close.textContent = t('Close'); close.addEventListener('click', () => dialog.close());
    const title = document.createElement('h2'); title.id = 'term-dialog-title'; title.textContent = term.term; header.append(title, close); dialog.append(header);
    for (const [en, ko, heading] of [[term.english, term.korean, 'Meaning'], [term.whyEn, term.whyKo, 'Why it matters / when to use it'], [term.exampleEn, term.exampleKo, 'Concrete situation (illustrative)'], [term.distinctionEn, term.distinctionKo, 'Do not confuse with']]) {
      if (!en || !ko) continue;
      const section = document.createElement('section'); const h3 = document.createElement('h3'); h3.textContent = t(heading); section.append(h3);
      if (heading === 'Concrete situation (illustrative)') {
        const steps = document.createElement('ol'); steps.className = 'term-scenario';
        const enSteps = en.split(' → '), koSteps = ko.split(' → ');
        for (const [index, label] of ['Situation', 'Apply', 'Check'].entries()) {
          const step = document.createElement('li'); step.dataset.scenarioStep = label.toLowerCase();
          const title = document.createElement('strong'); title.textContent = t(label); step.append(title);
          for (const [lang, value] of [['ko', koSteps[index]], ['en', enSteps[index]]]) {
            const p = document.createElement('p'); p.lang = lang; p.textContent = value; step.append(p);
          }
          steps.append(step);
        }
        section.append(steps);
      } else {
        for (const [lang, value] of [['ko', ko], ['en', en]]) {const p = document.createElement('p');p.lang = lang;p.textContent = value;section.append(p);}
      }
      dialog.append(section);
    }
    if (term.source) {const a = document.createElement('a'); a.href = term.source; a.textContent = t('Official documentation');a.target = '_blank';a.rel = 'noreferrer';dialog.append(a);}
    const chapter = document.createElement('a'); chapter.href = '#doc=' + (term.chapter ?? currentDocument.id); chapter.textContent = t('Read the explanation in context');chapter.addEventListener('click', () => dialog.close());dialog.append(chapter);
    dialog.showModal();
  };
  dialog.addEventListener('click', (event) => {if (event.target === dialog) {const r=dialog.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)dialog.close();}});
  const buttonFor = (term, label) => {const b=document.createElement('button');b.type='button';b.className='term-link';b.textContent=label;b.setAttribute('aria-haspopup','dialog');b.addEventListener('click',()=>openTerm(term));return b;};
  for (const term of terms) list.append(buttonFor(term, term.term));
  const aliases = terms.flatMap((term) => [term.term, ...(term.aliases ?? [])].filter((value) => value.length >= 2 && !value.includes(' / ')).map((alias) => ({alias, term}))).sort((a,b)=>b.alias.length-a.alias.length);
  if (!aliases.length) return;
  const pattern = new RegExp(`(?<![A-Za-z0-9_])(${aliases.map(({alias})=>escapePattern(alias)).join('|')})(?![A-Za-z0-9_])`, 'gi');
  const lookup = new Map(aliases.map(({alias,term})=>[alias.toLowerCase(),term]));
  const seen = new Set();
  const walker = document.createTreeWalker(article.querySelector('.markdown-body'), NodeFilter.SHOW_TEXT);
  const nodes = []; while(walker.nextNode()) nodes.push(walker.currentNode);
  for (const node of nodes) {
    if (node.parentElement.closest('a,pre,code,svg,button,summary')) continue;
    const lang = node.parentElement.closest('[lang]')?.lang ?? 'en';
    const fragment = document.createDocumentFragment(); let last = 0; let changed = false;
    for (const match of node.textContent.matchAll(pattern)) {
      const term = lookup.get(match[0].toLowerCase()), key = `${lang}:${term.term}`;
      if (seen.has(key)) continue;
      fragment.append(node.textContent.slice(last, match.index), buttonFor(term, match[0]));
      seen.add(key); last = match.index + match[0].length; changed = true;
    }
    if (changed) {fragment.append(node.textContent.slice(last));node.replaceWith(fragment);}
  }
}
